# Generated by Django 6.0.2 on 2026-02-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
